# Generated by Django 5.0.2 on 2024-03-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="tasklist",
            name="related",
        ),
        migrations.RemoveField(
            model_name="iscomplete",
            name="related",
        ),
        migrations.DeleteModel(
            name="DayList",
        ),
        migrations.DeleteModel(
            name="IsComplete",
        ),
        migrations.DeleteModel(
            name="TaskList",
        ),
    ]
